<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Claim extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = ['order_id', 'text'];

    const STATUSES = [
        "DRAFT" => 'draft',
        "VIEWED" => 'viewed',
        "APPROVED" => 'approved',
        "CANCELED" => 'canceled'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function (Claim $claim) {
            $claim->order->increaseClaimCounter();
        });
    }

    /**
     * Relations
     */

    public function documents()
    {
        return $this->hasMany(ClaimDocument::class);
    }

    public function order()
    {
        return $this->belongsTo(Order::class);
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * Scopes
     */

    public function scopeDraft($query)
    {
        return $query->where("status", self::STATUSES["DRAFT"]);
    }

    public function scopeViewed($query)
    {
        return $query->where("status", self::STATUSES["VIEWED"]);
    }

    public function scopeApproved($query)
    {
        return $query->where("status", self::STATUSES["APPROVED"]);
    }

    public function scopeCanceled($query)
    {
        return $query->where("status", self::STATUSES["CANCELED"]);
    }

    /**
     * Methods
     */

    public function setDocuments($documents)
    {
        $claim = $this;
        $data = array_map(function ($document) use ($claim) {
            return [
                'claim_id' => $claim->id,
                'url' => $document['url'],
                'type' => $document['type'],
                'file_size' => $document['file_size'] ?? null,
                'mime_type' => $document['mime_type'] ?? null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ];
        }, $documents);

        $docsToDelete = $this->documents()
            ->whereNotIn('url', array_column($data, 'url'))
            ->where("claim_id", $this->id)
            ->get();

        DB::transaction(function () use ($data, $docsToDelete, $claim) {
            $docsToDelete->each(function (ClaimDocument $document) {
                $document->delete();
            });

            $existedDocuments = $claim->documents()->get();

            foreach ($data as $row) {
                $existedDocument = $existedDocuments->where('url', $row['url'])
                    ->first();
                if ($existedDocument) {
                    ClaimDocument::query()
                        ->where('claim_id', $claim->id)
                        ->where("url", $row['url'])
                        ->update([
                            'type' => $row['type'],
                            'file_size' => $row['file_size'] ?? null,
                            'mime_type' => $row['mime_type'] ?? null,
                            'updated_at' => $row['updated_at']
                        ]);
                } else {
                    ClaimDocument::query()->insert($row);
                }
            }
        });
    }

    public function makeDraft()
    {
        $this->status = self::STATUSES["DRAFT"];
        $this->save();
    }

    public function viewed()
    {
        $this->status = self::STATUSES["VIEWED"];
        $this->save();
    }

    public function approve()
    {
        $this->status = self::STATUSES["APPROVED"];
        $this->save();
    }

    public function cancel()
    {
        $this->status = self::STATUSES["CANCELED"];
        $this->save();
    }
}
