<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class ClaimDocument extends Model
{
    use HasFactory;

    const TYPES = ['img', 'doc'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::deleting(function (ClaimDocument $document) {
            list('path' => $path) = parse_url($document->url);
            Storage::disk('s3')->delete($path);
        });
    }

    public function claim()
    {
        return $this->belongsTo(Claim::class);
    }
}
