<?php

namespace App\Models;

use App\Helpers\Mutator;
use App\Jobs\CompanyNotification\CompanyModerationFailed;
use App\Jobs\CompanyNotification\CompanyModerationPassed;
use App\Jobs\CompanyNotification\RatingDecreased;
use App\Jobs\CompanyNotification\RatingIncreased;
use App\Mail\RatingDecrease;
use App\Mail\RatingIncrease;
use App\Models\CompanyType;
use App\Services\CompanyRatingCalculator;
use Carbon\Carbon;
use Dadata\DadataClient;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;

class Company extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'company_type_id', 'inn', 'title', 'full_title', 'ogrn', 'kpp', 'okpo', 'legal_address', 'address', 'director', 'phone', 'email', 'website', 'description'
    ];

    protected $hidden = ['last_online_datetime'];

    protected $appends = ['viewable_reg_number'];

    protected $casts = ['approved_at' => 'datetime'];

    const SHOW_FOR_GUESTS = [
        "companies.id",
        "companies.created_at",
        "companies.rating",
        "companies.reg_number",
        "companies.verified",
        "companies.title",
        "companies.full_title",
        "companies.moderation_status",
        "companies.company_type_id",
    ];

    const MODERATION_STATUSES = [
        "DRAFT" => 'draft',
        "MODERATION" => 'moderation',
        "APPROVED" => 'approved',
        "CANCELED" => 'canceled'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (Company $company) {
            $company->generateFreeRegNumber();

            $company->setLegalRegistrationDate();
            
            // Если тип компании не указан, устанавливаем "Заказчик" по умолчанию
            if (!$company->company_type_id) {
                $customerType = CompanyType::where('title', 'Заказчик')->first();
                if ($customerType) {
                    $company->company_type_id = $customerType->id;
                }
            }
        });

        self::created(function (Company $company) {
            $company->makeAuthUserBoss();
        });

        self::updating(function (Company $company) {
            if ($company->isDirty('inn')) {
                $company->setLegalRegistrationDate();
            }
        });

        self::updated(function (Company $company) {
            if ($oldRating = $company->getOriginal('rating') !== $company->rating) {
                dispatch((float)$oldRating > $company->rating ? new RatingDecreased($company) : new RatingIncreased($company));

                if (NotificationTypeUser::isEnabled($company->boss->id, "personal", 'email')) {
                    $email = $company->boss?->getRawOriginal('email');
                    if ($email) Mail::to($email)->later(now()->addSeconds($company->boss->getSilenceDelay()), (float)$oldRating > $company->rating ? new RatingDecrease($company) : new RatingIncrease($company));
                }
            }
        });

        self::softDeleted(function (Company $company) {
            $company->orders->each(function (Order $order) {
                $order->delete();
            });
        });
    }

    /**
     * Relations
     */

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function type()
    {
        return $this->belongsTo(CompanyType::class, 'company_type_id');
    }

    public function vehicleTypes()
    {
        return $this->belongsToMany(VehicleType::class);
    }

    public function documents()
    {
        return $this->hasMany(CompanyDocument::class);
    }

    public function notifications()
    {
        return $this->hasMany(CompanyNotification::class);
    }

    public function photoGroups()
    {
        return $this->hasMany(PhotoGroup::class);
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function activeOrders()
    {
        return $this->orders()->active();
    }

    public function recommendations()
    {
        return $this->hasMany(Recommendation::class);
    }

    public function approvedRecommendations()
    {
        return $this->recommendations()->approved();
    }

    public function reports()
    {
        return $this->hasMany(Report::class);
    }

    public function activeReports()
    {
        // todo change method to confirmedReports -> ask ios/android to change key
        return $this->reports()->confirmed();
    }

    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function boss()
    {
        return $this->hasOne(User::class)->where("company_role", User::COMPANY_ROLES[1]);
    }

    public function reservedNumber()
    {
        return $this->hasOne(ReservedNumber::class);
    }

    public function awards()
    {
        return $this->belongsToMany(Award::class);
    }

    public function orderOffers(): HasMany
    {
        return $this->hasMany(OrderOffer::class);
    }

    /**
     * Scopes
     */

    public function scopeFailed(Builder $builder): Builder
    {
        return $builder->where("moderation_status", self::MODERATION_STATUSES["CANCELED"]);
    }

    public function scopePublished(Builder $builder): Builder
    {
        return $builder->where("moderation_status", self::MODERATION_STATUSES["APPROVED"]);
    }

    public function scopeOnModeration(Builder $builder): Builder
    {
        return $builder->where("moderation_status", self::MODERATION_STATUSES["MODERATION"]);
    }

    public function scopeDraft(Builder $builder): Builder
    {
        return $builder->where("moderation_status", self::MODERATION_STATUSES["DRAFT"]);
    }


    public function scopeInCities(Builder $builder, array $citiesId): Builder
    {
        if (count($citiesId) === 0) return $builder;
        return $builder->whereHas('boss', function ($q) use ($citiesId) {
            $q->whereIn("geo_city_id", $citiesId);
        });
    }

    public function scopeWithVehicles(Builder $builder, array $vehicleTypesId): Builder
    {
        if (count($vehicleTypesId) === 0) return $builder;
        return $builder->whereHas('vehicleTypes', function (Builder $query) use ($vehicleTypesId) {
            $query->whereIn("vehicle_types.id", $vehicleTypesId);
        });
    }

    public function scopeWithoutVehicles($q)
    {
        return $q->doesntHave("vehicleTypes");
    }

    public function scopeSearch(Builder $query, string $needle): Builder
    {
        $searchFields = ['inn', 'title', 'full_title', 'ogrn', 'kpp', 'okpo', 'phone', 'email', 'website'];
        return $query->where(function (Builder $q) use ($needle, $searchFields) {
            foreach ($searchFields as $k => $field) {
                if ($k === 0) {
                    $q->where($field, "like", "%$needle%");
                } else {
                    $q->orWhere($field, "like", "%$needle%");
                }
            }
            $q->orWhere("reg_number", "=", $needle);
        })->orWhereHas("reservedNumber", function ($q) use ($needle) {
            $q->where("number", $needle);
        });
    }

    /**
     * accessors, mutators
     */

    public function getTitleAttribute($value)
    {
        //if (auth('sanctum')->guest()) return "Название компании";
        return $value;
    }

    public function getFullTitleAttribute($value)
    {
        if (auth('sanctum')->guest()) return "Название компании";
        return $value;
    }

    public function getLegalRegistrationDateAttribute($value)
    {
        if (!$value) return null;
        return Carbon::parse($value)->format("Y-m-d");
    }

    public function getMembershipFeePaidAtAttribute($value)
    {
        if (!$value) return null;
        return Carbon::parse($value)->format("Y-m-d");
    }

    public function getIsFavoriteAttribute()
    {
        return $this->boss?->is_favorite;
    }

    public function getPhoneAttribute($value)
    {
        /** @var User|null $user */
        $user = auth('sanctum')->user();
        if ($user && $user->allowedToShowContacts()) {
            if (!$value) return null;
            return Mutator::numberToDigits($value);
        }
        return "* * * * * *";
    }

    public function getEmailAttribute($value)
    {
        /** @var User|null $user */
        $user = auth('sanctum')->user();
        if ($user && $user->allowedToShowContacts()) return $value;
        return '* * * * * *';
    }

    public function getViewableRegNumberAttribute($value)
    {
        if ($this->reservedNumber) {
            return $this->reservedNumber->number;
        }
        return $this->reg_number;
    }

    public function getRatingAttribute($value)
    {
        return round($value * 10) / 10;
    }

    public function getVehicleTypesIdAttribute()
    {
        if ($types = $this->vehicleTypes) {
            return $types->pluck("id");
        }
        return [];
    }

    /**
     * Methods
     */

    public function makeAuthUserBoss()
    {
        $user = auth()->user();
        if (!$user) return;
        if (!$user->isUser()) return;
        $user->company_id = $this->id;
        $user->company_role = User::COMPANY_ROLES[1];
        $user->save();
    }

    public function setDocuments($documents)
    {
        $company = $this;
        $data = array_map(function ($document) use ($company) {
            return [
                'company_id' => $company->id,
                'url' => $document['url'],
                'type' => $document['type'],
                'file_size' => $document['file_size'] ?? null,
                'mime_type' => $document['mime_type'] ?? null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ];
        }, $documents);

        $docsToDelete = $this->documents()
            ->whereNotIn('url', array_column($data, 'url'))
            ->where("company_id", $this->id)
            ->get();

        $canDeleteDocuments = $this->moderation_status !== self::MODERATION_STATUSES["APPROVED"] || Gate::allows('moderate', $company);

        DB::transaction(function () use ($data, $docsToDelete, $company, $canDeleteDocuments) {
            if ($canDeleteDocuments) {
                $docsToDelete->each(function (CompanyDocument $document) {
                    $document->delete();
                });
            }

            $existedDocuments = $company->documents()->get();
            foreach ($data as $row) {
                $existedDocument = $existedDocuments
                    ->where('url', $row['url'])
                    ->first();

                if ($existedDocument) {
                    CompanyDocument::query()
                        ->where('company_id', $company->id)
                        ->where("url", $row['url'])
                        ->update([
                            'type' => $row['type'],
                            'file_size' => $row['file_size'] ?? null,
                            'mime_type' => $row['mime_type'] ?? null,
                            'updated_at' => $row['updated_at']
                        ]);
                } else {
                    CompanyDocument::query()->insert($row);
                }
            }
        });
    }

    public function makeDraft()
    {
        $this->moderation_status = self::MODERATION_STATUSES["DRAFT"];
        $this->moderation_message = null;
        $this->save();
    }

    public function sendOnModeration()
    {
        $this->moderation_status = self::MODERATION_STATUSES["MODERATION"];
        $this->moderation_message = null;
        $this->save();
    }

    public function passModeration()
    {
        $this->moderation_status = self::MODERATION_STATUSES["APPROVED"];
        $this->moderation_message = null;
        $this->approved_at = Carbon::now();
        $this->save();

        dispatch(new CompanyModerationPassed($this));

        if (NotificationTypeUser::isEnabled($this->boss->id, "personal", 'email')) {
            $email = $this->boss?->getRawOriginal('email');
            if ($email) Mail::to($email)->later(now()->addSeconds($this->boss->getSilenceDelay()), new \App\Mail\CompanyModerationPassed($this));
        }

        $this->attachBossesOrders();
    }

    public function failModeration($msg = null)
    {
        $this->moderation_status = self::MODERATION_STATUSES["CANCELED"];
        $this->moderation_message = $msg;
        $this->save();

        dispatch(new CompanyModerationFailed($this));
        $email = $this->boss?->getRawOriginal('email');
        if (NotificationTypeUser::isEnabled($this->boss->id, "personal", 'email')) {
            if ($email) Mail::to($email)->later(now()->addSeconds($this->boss->getSilenceDelay()), new \App\Mail\CompanyModerationFailed($this));
        }
    }

    protected function attachBossesOrders()
    {
        $boss = $this->boss;
        if (!$boss) return;
        Order::query()
            ->where('user_id', $boss->id)
            ->update(['company_id' => $this->id]);
    }

    public function isApproved(): bool
    {
        return $this->moderation_status === self::MODERATION_STATUSES["APPROVED"];
    }

    public function calculateRating(): float
    {
        $calculator = new CompanyRatingCalculator($this);
        return $calculator->getScore();
    }

    public function getRatingDetails(): array
    {
        $calculator = new CompanyRatingCalculator($this);
        return $calculator->getDetails();
    }

    public function updateRating()
    {
        $this->rating = $this->calculateRating();
        $this->save();

        User::query()->where("company_id", $this->id)
            ->update(['rating' => $this->rating]);
    }

    public function generateFreeRegNumber()
    {
        $busyNumbers = Company::query()->pluck("reg_number")->filter()->values();
        $reservedNumbers = ReservedNumber::query()->pluck("number")->filter()->values();
        $allClosedNumbers = $busyNumbers->merge($reservedNumbers)->toArray();
        $allClosedNumbers = array_map('intval', $allClosedNumbers);

        do {
            $randNumber = random_int(100000, 999999);
        } while (in_array($randNumber, $allClosedNumbers));

        $this->reg_number = $randNumber;
    }

    public function setLegalRegistrationDate()
    {

        $dadata = new DadataClient(config('services.dadata.key'), config('services.dadata.secret'));
        $result = $dadata->findById("party", $this->inn, 1);
        if (count($result) === 0) return;
        $companyData = $result[0];
        try {
            $regDate = $companyData['data']['state']['registration_date'];
        } catch (\Exception $e) {
            return;
        }
        if (!$regDate) return;

        $date = Carbon::createFromTimestamp($regDate / 1000);
        $this->legal_registration_date = $date;
    }
}
