<?php

namespace App\Models;

use App\Events\ChatListUpdated;
use App\Jobs\CompanyNotification\NewMessage;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Message extends Model
{
    use HasFactory;

    protected $fillable = ['chat_id', 'author_id', 'text', 'file_type', 'file_url', 'reply_message_id'];

    protected $appends = ['is_mine'];

    const FILE_TYPES = ['doc', 'img', 'video'];

    protected $casts = [
        "sent_at" => "datetime",
        "delivered_at" => "datetime",
        "read_at" => "datetime",
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function (Message $message) {
            $chat = $message->chat;
            if ($chat->report_id) {
                dispatch(new NewMessage($message));
            }

            if ($chat->order_id) {
                $targetUsers = $chat->users()
                    ->where("users.id", "!=", $message->author_id)
                    ->wherePivotNull("muted_at")
                    ->wherePivotNull("blocked_at")
                    ->get();

                foreach ($targetUsers as $targetUser) {
                    dispatch(new \App\Jobs\Chat\NewChatMessage($targetUser, $message));
                }

                broadcast(new ChatListUpdated($targetUsers->pluck("id")->toArray(), $chat->id));
            }
        });
    }

    /**
     * Relations
     */

    public function chat()
    {
        return $this->belongsTo(Chat::class);
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'author_id');
    }

    public function repliedMessage()
    {
        return $this->belongsTo(Message::class, 'reply_message_id');
    }

    /**
     * Scopes
     */

    public function scopeVisible($q, $blockedAt)
    {
        if (!$blockedAt) return $q;
        return $q->where("created_at", "<=", $blockedAt);
    }

    /**
     * Accessors/ Mutators
     */

    public function getIsMineAttribute()
    {
        return $this->author_id === auth()->id();
    }

    /**
     * Methods
     */

    public static function getTotalNewMessagesCount($user_id = null): int
    {
        if (!$user_id) {
            $user_id = auth()->id();
        }

        // count only ACTIVE + REFEREE reports?
        $data = DB::selectOne("select count(*) as count
from chat_user cu
         join messages m on m.chat_id = cu.chat_id and case
                                                           when cu.last_seen_at is null then 1
                                                           when cu.last_seen_at is not null
                                                               then m.created_at > cu.last_seen_at end
         join chats c on cu.chat_id = c.id
         join reports r on c.report_id = r.id
where r.status in ('active', 'referee')
  and cu.user_id = $user_id
  and m.author_id != $user_id;");
        return $data->count;
    }

    public static function getOutReportsNewMessagesCount(User $user): int
    {
        $data = DB::selectOne("select count(*) as count
from chat_user cu
         join messages m on m.chat_id = cu.chat_id and case
                                                           when cu.last_seen_at is null then 1
                                                           when cu.last_seen_at is not null
                                                               then m.created_at > cu.last_seen_at end
         join chats c on cu.chat_id = c.id
         join reports r on c.report_id = r.id
    where r.status in ('draft','active', 'referee')
    and cu.user_id = $user->id
    and m.author_id != $user->id
    and r.author_user_id = $user->id ;");
        return $data->count;
    }

    public static function getInReportsNewMessagesCount(User $user): int
    {
        $sql = "select count(*) as count
from chat_user cu
         join messages m on m.chat_id = cu.chat_id and case
                                                           when cu.last_seen_at is null then 1
                                                           when cu.last_seen_at is not null
                                                               then m.created_at > cu.last_seen_at end
         join chats c on cu.chat_id = c.id
         join reports r on c.report_id = r.id
    where r.status != 'draft'
    and m.author_id != $user->id
    and cu.user_id = $user->id
    and r.target_user_id = $user->id";

        if ($user->isBoss()) {
            $sql .= " and (r.target_user_id = $user->id or r.company_id = $user->company_id)";
        } else {
            $sql .= " and r.target_user_id = $user->id";
        }

        $data = DB::selectOne($sql);
        return $data->count;
    }

    public static function orderNewMessagesCount(User $user): int
    {
        $sql = "select count(*) as count
from chat_user cu
         join messages m on m.chat_id = cu.chat_id and case
                                                           when cu.last_seen_at is null then 1
                                                           when cu.last_seen_at is not null
                                                               then m.created_at > cu.last_seen_at end
         join chats c on cu.chat_id = c.id

    where m.author_id != $user->id
    and cu.user_id = $user->id
    and c.order_id is not null
    ";

        $data = DB::selectOne($sql);
        return $data->count;
    }
}
