<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class OrderDocument extends Model
{
    use HasFactory;

    protected $fillable = ['type', 'url', 'order_id', 'file_size', 'mime_type'];

    const TYPES = ['doc', 'img', 'video'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::deleting(function (OrderDocument $document) {
            list('path' => $path) = parse_url($document->url);
            Storage::disk('s3')->delete($path);
        });
    }

    public function order()
    {
        return $this->belongsTo(Order::class);
    }
}
