<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
    use HasFactory;

    protected $fillable = [
        'type', 'hidden', 'title', 'content', 'path', 'order', 'seo_title', 'seo_description', 'seo_keywords'
    ];

    //o   О сервисе
    //o   Начало работы
    //o   Заказчикам
    //o   Исполнителям
    //o   Рейтинги
    const FAQ_CATEGORIES = [
        ['path' => '/', 'label' => 'О сервисе'],
        ['path' => '/get-started', 'label' => 'Начало работы'],
        ['path' => '/to-customers', 'label' => 'Заказчикам'],
        ['path' => '/to-companies', 'label' => 'Исполнителям'],
        ['path' => '/rating', 'label' => 'Рейтинги',]
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (Page $page) {
            $page->setAttribute('hidden', 0);
            $page->order = Page::query()->type($page->type)->count();
        });
    }

    public function scopeActive($q)
    {
        return $q->where("hidden", false);
    }

    public function scopeType($q, $type)
    {
        return $q->where("type", "=", $type);
    }
}
