<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Photo extends Model
{
    use HasFactory;

    protected $fillable = ['url', 'created_at', 'description', 'photo_group_id'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::deleting(function (Photo $photo) {
            list('path' => $path) = parse_url($photo->url);
            Storage::disk('s3')->delete($path);
        });
    }

    public function group()
    {
        return $this->belongsTo(PhotoGroup::class);
    }
}
