<?php

namespace App\Models;

use App\Jobs\CompanyNotification\RefereeMadeDecision;
use App\Jobs\CompanyNotification\ReportCreated;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;

class Report extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = ['report_type_id', 'author_user_id', 'company_id', 'target_user_id', 'order_id', 'amount', 'text', 'status'];

    const STATUSES = [
        'DRAFT' => 'draft', // черновик
        "ACTIVE" => 'active', // новая претензия (не подтверждена)
        "REFEREE" => 'referee', // вызван арбитр
        "CONFIRMED" => 'confirmed', // подтверждена
        "REJECTED" => 'rejected', // отклонена
        "RESOLVED" => 'resolved', // урегулирована
        "CANCELED" => 'canceled', // удалена (отозвана, архив)
    ];

    protected $appends = ['new_messages_count'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::updated(function (Report $report) {
            if ($report->status === self::STATUSES["ACTIVE"]) {
                if (!$report->chat) {
                    $report->createChat();
                }
            }
        });

        self::forceDeleted(function (Report $report) {
            if ($chat = $report->chat()->first()) {
                $chat->delete();
            }
        });
    }

    /**
     * Relations
     */

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'author_user_id');
    }

    public function targetUser()
    {
        return $this->belongsTo(User::class, 'target_user_id');
    }

    public function order()
    {
        return $this->belongsTo(Order::class);
    }

    public function type()
    {
        return $this->belongsTo(ReportType::class, 'report_type_id');
    }

    public function documents()
    {
        return $this->hasMany(ReportDocument::class);
    }

    public function chat()
    {
        return $this->hasOne(Chat::class, 'report_id');
    }

    /**
     * Scopes
     */
    public function scopeDraft(Builder $query): Builder
    {
        return $query->where("status", "=", self::STATUSES["DRAFT"]);
    }

    public function scopeActive(Builder $query): Builder
    {
        return $query->where("status", self::STATUSES["ACTIVE"]);
    }

    public function scopeReferee(Builder $query): Builder
    {
        return $query->where("status", "=", self::STATUSES["REFEREE"]);
    }

    public function scopeConfirmed(Builder $query): Builder
    {
        return $query->where("status", "=", self::STATUSES["CONFIRMED"]);
    }

    public function scopeRejected(Builder $query): Builder
    {
        return $query->where("status", "=", self::STATUSES["REJECTED"]);
    }

    public function scopeResolved(Builder $query): Builder
    {
        return $query->where("status", "=", self::STATUSES["RESOLVED"]);
    }

    public function scopeCanceled(Builder $query): Builder
    {
        return $query->where("status", "=", self::STATUSES["CANCELED"]);
    }

    public function scopeNotCanceled(Builder $query): Builder
    {
        return $query->where("status", "!=", self::STATUSES["CANCELED"]);
    }

    public function scopeNotClosed(Builder $query): Builder
    {
        return $query->whereIn("status", [self::STATUSES["DRAFT"], self::STATUSES["ACTIVE"], self::STATUSES["REFEREE"]]);
    }

    public function scopeClosed(Builder $query): Builder
    {
        return $query->whereIn("status", [self::STATUSES["CONFIRMED"], self::STATUSES["REJECTED"], self::STATUSES["RESOLVED"]]);
    }

    public function scopeVisible(Builder $query): Builder
    {
        return $query->where(function (Builder $q) {
            $q->byMe()->orWhere("status", "!=", self::STATUSES["DRAFT"]);
        });
    }

    public function scopeByMe(Builder $query): Builder
    {
        return $query->where("author_user_id", auth()->id());
    }

    public function scopeToMe(Builder $query): Builder
    {
        return $query->visible()->where(function (Builder $q) {
            $q->where("target_user_id", auth()->id());
            if (auth()->user()->isBoss()) {
                $q->orWhere("company_id", auth()->user()->company_id);
            }
        });
    }

    public function scopeSearch(Builder $query, string $searchString): Builder
    {
        return $query->where(function (Builder $q) use ($searchString) {
            $q->where("text", "like", "%$searchString%")
                ->orWhereHas("author", function ($q) use ($searchString) {
                    $q->search($searchString);
                })->orWhereHas('targetUser', function ($q) use ($searchString) {
                    $q->search($searchString);
                })->orWhereHas('company', function ($q) use ($searchString) {
                    $q->search($searchString);
                });
        });
    }

    /**
     * Accessors, Mutators
     */

    public function getNewMessagesCountAttribute(): int
    {
        if (!$chat = $this->chat) {
            return 0;
        }
        $pivot = DB::table('chat_user')
            ->where('chat_id', $chat->id)
            ->where('user_id', auth()->id())->first();

        if (!$pivot) {
            return 0;
        }

        if (!$lastSeenAt = $pivot->last_seen_at) {
            return $chat->messages()->count();
        }

        return $chat->messages()->where('created_at', '>', $lastSeenAt)
            ->where('author_id', '!=', auth()->id())->count();
    }

    /**
     * Methods
     */

    public function setDocuments($documents)
    {
        $report = $this;
        $data = array_map(function ($document) use ($report) {
            return [
                'report_id' => $report->id,
                'url' => $document['url'],
                'type' => $document['type'],
                'file_size' => $document['file_size'] ?? null,
                'mime_type' => $document['mime_type'] ?? null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()

            ];
        }, $documents);


        $docsToDelete = $this->documents()
            ->whereNotIn('url', array_column($data, 'url'))
            ->where("report_id", $this->id)
            ->get();

        DB::transaction(function () use ($data, $docsToDelete, $report) {

            $docsToDelete->each(function (ReportDocument $document) {
                $document->delete();
            });

            $existedDocuments = $this->documents()->get();

            foreach ($data as $row) {
                $existedDocument = $existedDocuments->where('url', $row['url'])
                    ->first();
                if ($existedDocument) {
                    ReportDocument::query()
                        ->where('report_id', $report->id)
                        ->where("url", $row['url'])
                        ->update([
                            'type' => $row['type'],
                            'file_size' => $row['file_size'] ?? null,
                            'mime_type' => $row['mime_type'] ?? null,
                            'updated_at' => $row['updated_at']
                        ]);
                } else {
                    ReportDocument::query()->insert($row);
                }
            }
        });
    }


    public function createChat(): Chat
    {
        $chat = new Chat(['report_id' => $this->id]);
        $chat->save();

        $chat->inviteParties();

        return $chat;
    }

    public function makeDraft()
    {
        $this->status = self::STATUSES["DRAFT"];
        $this->save();
    }

    public function moderate()
    {
        $this->status = self::STATUSES["ACTIVE"];
        $this->save();

        dispatch(new ReportCreated($this));

        if (NotificationTypeUser::isEnabled($this->target_user_id, "personal", 'email')) {
            $email = $this->targetUser?->getRawOriginal('email');
            if ($email) Mail::to($email)->later(now()->addSeconds($this->targetUser->getSilenceDelay()), new \App\Mail\ReportCreated($this));
        }
    }

    public function referee()
    {
        $this->status = self::STATUSES["REFEREE"];
        $this->save();

    }

    public function confirm()
    {
        $this->status = self::STATUSES["CONFIRMED"];
        $this->save();

        dispatch(new RefereeMadeDecision($this));

        if (NotificationTypeUser::isEnabled($this->targetUser->id, "personal", 'email')) {
            $targetEmail = $this->targetUser?->getRawOriginal('email');
            if ($targetEmail) Mail::to($targetEmail)->later(now()->addSeconds($this->targetUser->getSilenceDelay()), new \App\Mail\RefereeMadeDecision($this, $this->targetUser));
        }

        if (NotificationTypeUser::isEnabled($this->author->id, "personal", 'email')) {
            $authorEmail = $this->author?->getRawOriginal('email');
            if ($authorEmail) Mail::to($authorEmail)->later(now()->addSeconds($this->author->getSilenceDelay()), new \App\Mail\RefereeMadeDecision($this, $this->author));
        }
    }

    public function reject()
    {
        $this->status = self::STATUSES["REJECTED"];
        $this->save();

        dispatch(new RefereeMadeDecision($this));

        if (NotificationTypeUser::isEnabled($this->targetUser->id, "personal", 'email')) {
            $targetEmail = $this->targetUser?->getRawOriginal('email');
            if ($targetEmail) Mail::to($targetEmail)->later(now()->addSeconds($this->targetUser->getSilenceDelay()), new \App\Mail\RefereeMadeDecision($this, $this->targetUser));
        }

        if (NotificationTypeUser::isEnabled($this->author->id, "personal", 'email')) {
            $authorEmail = $this->author?->getRawOriginal('email');
            if ($authorEmail) Mail::to($authorEmail)->later(now()->addSeconds($this->author->getSilenceDelay()), new \App\Mail\RefereeMadeDecision($this, $this->author));
        }
    }

    public function resolve()
    {
        $this->status = self::STATUSES["RESOLVED"];
        $this->save();
    }

    public function cancel()
    {
        $this->status = self::STATUSES["CANCELED"];
        $this->save();
    }
}
