<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class ReportDocument extends Model
{
    use HasFactory;

    protected $fillable = ['report_type_id', 'type', 'url'];

    const TYPES = ['doc', 'img', 'video'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::deleting(function (ReportDocument $document) {
            list('path' => $path) = parse_url($document->url);
            Storage::disk('s3')->delete($path);
        });
    }

    public function report()
    {
        return $this->belongsTo(Report::class);
    }
}
